services:
  derailed:
    container_name: derailed
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
      - mongosetup
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STORAGE_URI=redis://redis:6379
      - MONGODB_URI=mongodb://mongo:27017/?replicaSet=rs0

  redis:
    image: eqalpha/keydb
    restart: unless-stopped

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./.data/db:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]

  mongosetup:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./scripts/:/scripts/
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]
